---
title: "SOM_dodder_updated"
author: "Min-Yao"
date: "2020/11/02"
output: html_document
---

```{r}
library(class)
library(MASS)
library(kohonen)
library(ggplot2)
```

```{r}
###all
## Read in data
data <- read.table("pca.scores.LCM.txt",header=TRUE)
names(data)
head(data)
```

```{r}
## Create a matrix and scale data (data is already scaled, so nothing happens actually besides making a matrix)
m.data <- as.matrix(data[8:10])
sc.data <- t(scale(t(m.data)))
```

```{r}
## Set a random seed so that SOM results are reproducible
set.seed(2)
```

```{r}
## Perform SOM (6 x 2)
ssom <- som(sc.data, somgrid(3,2,"hexagonal"))
summary(ssom)
# som map of size 3x4 with a hexagonal topology.
# Training data included; dimension is 15664 by 6
# Mean distance to the closest unit in the map: 0.6107334
```

```{r}
ch <- ssom$changes
ch <- as.data.frame(ch)
ch$x <- c(1:100)

pdf("ssom.changes.LCM.3x2.pdf", width=8, height=8)
ggplot(ch,aes(x,V1))+geom_line(size=1.2,colour="grey30")+theme_bw()
dev.off()
#tiff("ssom.changes.LCM.3x2.tiff", width=8, height=8, unit="in",compression="lzw",res=100)
#ggplot(ch,aes(x,V1))+geom_line(size=1.2,colour="grey30")+theme_bw()
#dev.off()
```

```{r}
pdf("ssom.changes.3x2.pdf")
plot(ssom, type ="changes")
dev.off()

pdf("ssom.codes.3x2.pdf")
plot(ssom, type = "codes")
dev.off()

pdf("ssom.counts.3x2.pdf")
plot(ssom, type = "counts")
dev.off()

pdf("ssom.quality.3x2.pdf")
plot(ssom, type = "quality")
dev.off()
```

```{r}
## Create and write-out master SOM file
data.val2 <- cbind(data,ssom$unit.classif,ssom$distances)
head(data.val2)
write.csv(data.val2, file="supersom.data.LCM.3x2.csv")
```

```{r}
## Codes for the SOM nodes
codes <- ssom$codes
head(codes)
write.table(codes, file="codes.LCM.3x2.txt")
```

```{r}
## Visualization
data <- read.csv("supersom.data.LCM.3x2.csv",header=TRUE)
attach(data)
names(data)
tail(data)
```
```{r}
## PC graphs
library(ggplot2)

pdf("node.LCM.PC1PC2.3x2.pdf", width=8, height=6)
t <- ggplot(data, aes(PC1, PC2))
t + geom_point(alpha=0.4, size=2.5,aes(colour=factor(ssom.unit.classif))) + theme_bw() + 
scale_colour_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green"))
dev.off()

# pdf("node.LCM.PC3PC4.3x2.pdf", width=8, height=6)
# t <- ggplot(data, aes(PC3, PC4))
# t + geom_point(alpha=0.4,size=2.5, aes(colour=factor(ssom.unit.classif))) + theme_bw() +
# scale_colour_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green"))
# dev.off()
```

```{r}
## PC graphs
# library(ggplot2)
# 
# tiff("node.LCM.PC1PC2.3x2.tif", width=10, height=8, unit="in",compression="lzw",res=100)
# t <- ggplot(data, aes(PC1, PC2))
# t + geom_point(alpha=0.4, size=2.5,aes(colour=factor(ssom.unit.classif))) + theme_bw() + 
# scale_colour_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green"))
# dev.off()
# 
# tiff("node.LCM.PC3PC4.3x2.tif", width=10, height=8, unit="in",compression="lzw",res=100)
# t <- ggplot(data, aes(PC3, PC4))
# t + geom_point(alpha=0.4,size=2.5, aes(colour=factor(ssom.unit.classif))) + theme_bw() + 
# scale_colour_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green"))
# dev.off()
```

```{r}
## Boxplots for each node
# Node
library(reshape)

sub.group <- subset(data, ssom.unit.classif=="3")
expression <- sub.group[c(2,11,9,10)]
m.expression <- melt(expression, id=c("X")) # multiple column into one column
head(m.expression)

#tiff("node9.boxplot.LCM.3x2.tif", width=4, height=8, unit="in",compression="lzw",res=100)
pdf("node3.boxplot.LCM.3x2.pdf", width=4, height=8)
p <- ggplot(m.expression, aes(x=variable, y=value))
p + geom_point(position="jitter",size=1.5,alpha=0.6) + geom_boxplot(outlier.size=0, alpha=0.8) + theme_bw()
dev.off()
```

```{r}
## Loess regression lines for all nodes
# used iplant

expression <- data[c(2,11,9,10,15)]
m.expression <- melt(expression, id=c("X","ssom.unit.classif"))
#tiff("loes.lines.tif", width=32, height=16, unit="in",compression="lzw",res=250)
pdf("loes.lines.3x2.pdf", width=10, height=5)
p <- ggplot(m.expression, aes(x=variable, y=value, color=factor(ssom.unit.classif),group=ssom.unit.classif))
p + theme_bw() + 
stat_smooth(method="loess",aes(fill=factor(ssom.unit.classif)),alpha=0.4,size=1,span = 0.4) +
scale_colour_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green")) +
scale_fill_manual(values=c("red2","springgreen3","blue3","gray60","magenta3","yellow4","turquoise2","deeppink1","black","palegreen4","yellow","green"))
dev.off()
```

```{r}
## heatmap
library(gplots)
library(RColorBrewer)

h.data <- subset(data[c(11,9,10,15)])
rownames(h.data) <- data[,2]
#sh.data <- h.data[order(h.data$ssom.unit.classif),]

hmcol <- colorRampPalette(brewer.pal(11, "RdBu"))(64)
#hmcol <- colorRampPalette( colors = brewer.pal(10,"RdBu") )
#hmcol <- colorRampPalette( c("blue","white","red"))(10)

cluster = 3
data.c<- subset(h.data,h.data$ssom.unit.classif==cluster)
data.c <- subset(data.c[c(1,2,3)])

#tiff(paste("heatmap.cluter",cluster,".tif"), width=4, height=10, unit="in",compression="lzw",res=200)
pdf(paste("3x2.heatmap.cluter",cluster,".pdf"), width=2, height=5)
heatmap.2(as.matrix(data.c),col=rev(hmcol),scale="row",dendrogram="none",
          key=FALSE,keysize=0.5,density.info="none",trace="none",cexCol=0.5,labRow=NA,Colv=FALSE)
dev.off()

#tiff("key.tif")
pdf("3x2.key.pdf")
key <- display.brewer.pal(11, "RdBu")
dev.off()

table(h.data$ssom.unit.classif)
#1    2    3    4    5    6    7    8    9   10   11   12 
#468 2179  870 1733 1498 1551 3909  573  881  661  587  754 


```

